{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "static-content.serviceAccountName" . }}
  labels:
{{ include "static-content.labels" . | indent 4 }}
{{- end -}}
