{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "companynews.serviceAccountName" . }}
  labels:
{{ include "companynews.labels" . | indent 4 }}
{{- end -}}
